import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";

const inria_sans = Inria_Sans({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Boinks Budgeting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inria_sans.className}>{children}</body>
    </html>
  );
}
